### PR TITLE
Changed imresize to pillow.resize

### PR DESCRIPTION
**Pull request by akoen**
image

This should be the correct fix, but both master and my branch fail the above test. Since I don't have a passing implementation to compare to, I'd appreciate it if someone could run my code on their end.

### CODE REVIEW

**Comment by SilentSys** [comment]
@ADSteele916 @ADungate Why do I vaguely remember us already making these changes? I'm spooked now at how they didnt make it in.

**Comment by SilentSys** [comment]
Ah, it was #22, it was done for the marker and the map was missed.

**Review by SilentSys — APPROVED** [review]
The tests pass on my machine. Weird that it doesn't pass on yours. Did you set up your mapbox api key?

Thanks for fixing this 🚀

**Comment by akoen** [comment]
Yes, I believe so. If I can see the map, does that mean that my API key is working?

Will test again in the coming days.

**Comment by SilentSys** [comment]
Yeah, that means your key is working.

**Pull request merged**
