### PR TITLE
Simulate sensors using SIM

### PR DESCRIPTION
**Pull request by akoen**
In progress (have not written any tests)

Allows the FW and SW to communicate sensor data over SIM.

See also https://github.com/UBC-Rocket/FLARE/pull/128

### CODE REVIEW

**Review by SilentSys — CHANGES_REQUESTED** [review]
Looks great, very clean! Just a few comments answering your question and future stuff.

So what's next for this PR, do you want to get it in as is or do you want to start building up sensor features and tests? We can make new tasks for those if you want as I think they require some extra architectural decision making.

**Comment by SilentSys** [comment]
[Replace data csv with SIM request to GS](https://trello.com/c/kRyuBnwe/244-replace-data-csv-with-sim-request-to-gs)

**Comment by akoen** [comment]
I've gone ahead and made each sensor its own class and then assigning a map between each sensor's ID and itself.

Is this the cleanest way to do it?

P.S I've got it working with all the sensors now :)
image

**Review by SilentSys — APPROVED** [review]
> I've gone ahead and made each sensor its own class and then assigned a map between each sensor's ID and itself.
> 
> Is this the cleanest way to do it?
> 
> P.S I've got it working with all the sensors now :)
> image

Looks good to me!

I've been working on refactoring of the rocket profiles. Part of the refactoring I've done is to help with the defining of HW in the profile itself since this may vary between rockets. Let's get these changes merged ASAP, then I'll pull out the sensor definitions, put them in the rocket profiles and open a PR with all my changes.

I'll leave this PR open for another day or so in case anybody else wants to review it, then I'll merge it.

**Review by DSep — APPROVED** [review]
LGTM.
Interested to see its integration into rocket profile refactors that are coming!

**Review by ADSteele916 — APPROVED** [review]
LGTM

**Comment by SilentSys** [comment]
[Remove .vscode from the repository](https://trello.com/c/bBcUN9yR/251-remove-vscode-from-the-repository)

**Pull request merged**
