### PR TITLE
Event stats, radio packet integration tests with debug connection

### PR DESCRIPTION
**Pull request by SilentSys**
- Implemented event_stats module and used it in all tests that depended on sleeps
     - event_stats will likely be very useful in every integration test we write as it allows us to wait until threads process data before asserting on their results
- Radio packet integration tests with debug connection

### CODE REVIEW

**Review by DSep — APPROVED** [review]
Looks good, but to properly understand I think I'll need a run down of the new debug system next meeting.
Really nice to have those debug packet creators extracted like that. I hope it'll be okay (design-wise) to use them in SIM tests potentially too?

And if I'm not mistaken the events appear to be global objects following a different design pattern than usual, but are nicely done and very convenient. I'll have to hear the design process and reasoning next meeting.

**Comment by SilentSys** [comment]
@DSep Sounds good, look forward to chatting about it next meeting.

**Review by DSep — APPROVED** [review]
LGTM! Thanks for explaining the pieces during the call. It's pretty cool stuff! 
And nice functional moves Alex 😄

**Review by ADSteele916 — APPROVED** [review]
LGTM

**Pull request merged**
