### PR TITLE
Parameterized integration tests for multiple devices and profiles

### PR DESCRIPTION
**Pull request by SilentSys**
With the TantalusStage2 target being recently added to the FLARE repo and more to come soon, the scope of these chances was to add a framework for parametrizing the SIM tests so that we can test all FLARE targets. Additionally, this is part of the required foundation for the soon-to-come full flight tests.

Most relevant changes are in tests/integration_tests/test_sim.py. Other changes are just to facilitate that.

### CODE REVIEW

**Comment by SilentSys** [comment]
[Rocket specific integration tests & parametrized general integration tests](https://trello.com/c/qKyM66hA/307-rocket-specific-integration-tests-parametrized-general-integration-tests)

**Comment by SilentSys** [comment]
[Add TantalusStage2 SIM to rocket profile & fix rocket specific event waiting](https://trello.com/c/EeO8YxdP/298-add-tantalusstage2-sim-to-rocket-profile-fix-rocket-specific-event-waiting)

**Review by ADSteele916 — APPROVED** [review]
LGTM

**Review by DSep — APPROVED** [review]
Love this sort of refactor 👍

**Pull request merged**
