### PR TITLE
Multiple connections support & rocket-specific packet parsers

### PR DESCRIPTION
**Pull request by SilentSys**
Sorry once again for the massive PR. Don't think anyone has the time to review the whole thing tbh.

Key notes:

- PacketParser inheritance & defined in rocket profile
- Request a config packet (handshake) at start.
- DeviceManager keeps track of all connected devices
- General multi-device support everywhere

More info about handshake and multi-device here http://confluence.ubcrocket.com/display/AV/Specs#Specs-Policies

### CODE REVIEW

**Comment by SilentSys** [comment]
[Handle rocket specific parsing](https://trello.com/c/FQEDCCeV/276-handle-rocket-specific-parsing)

**Comment by SilentSys** [comment]
[Support for multiple connections](https://trello.com/c/AnFA9dO5/272-support-for-multiple-connections)

**Comment by SilentSys** [comment]
Removed the concept of "HWID". In hindsight, it was a horrible idea. Now using `FullAddress` -- named tuple of `(connection_name, device_address)' -- instead.

**Review by akoen — APPROVED** [review]
Gave it a pretty cursory overview but nothing seems wrong and the branch runs great on my computer.

**Review by DSep — APPROVED** [review]
Looks pretty great, works on my machine. At the end of running the self test I did get: "/var/folders/0n/86zx88655s1cj_4s99x6vdsc0000gn/T/_MEIGkcdCR/multiprocessing/semaphore_tracker.py:144: UserWarning: semaphore_tracker: There appear to be 6 leaked semaphores to clean up at shutdown" which you might be aware of already.

Pretty extensive changes, which are awesome. I do wanna get a better idea of everything that's changed though, so I might need to ask about a few things (eg the rocket data call back lock, how device management will be interfaced by incoming features and code). And also do want to have a more general discussion on rocket data's future soon.

**Pull request merged**
