### PR TITLE
Removed config packet length field to match spec

### PR DESCRIPTION
**Pull request by SilentSys**

### CODE REVIEW

**Review by DSep — COMMENTED** [review]
Is this necessary as a separate PR? These changes and more are in the radio controller redesign branch already. Does it need to be expedited? 

See: https://github.com/UBC-Rocket/UBCRocketGroundStation/tree/radioControllerRedesign

1: https://github.com/UBC-Rocket/UBCRocketGroundStation/blob/e41542bed369e8aa8349a475c859601d723e7cf5/connections/debug/radio_packets.py#L98

2 https://github.com/UBC-Rocket/UBCRocketGroundStation/blob/e41542bed369e8aa8349a475c859601d723e7cf5/main_window/packet_parser.py#L46

**Comment by SilentSys** [comment]
> Is this necessary as a separate PR? These changes and more are in the radio controller redesign branch already. Does it need to be expedited?
> 
> See: https://github.com/UBC-Rocket/UBCRocketGroundStation/tree/radioControllerRedesign
> 
> 1:
> 
> https://github.com/UBC-Rocket/UBCRocketGroundStation/blob/e41542bed369e8aa8349a475c859601d723e7cf5/connections/debug/radio_packets.py#L98
> 
> 2
> 
> https://github.com/UBC-Rocket/UBCRocketGroundStation/blob/e41542bed369e8aa8349a475c859601d723e7cf5/main_window/packet_parser.py#L46

Oh darn, sorry I didn't realize you had made those changes as well, my bad.

I just needed this so that I could get https://github.com/UBC-Rocket/FLARE/pull/124 in. I'm okay holding this PR off until you get your branch merged though. You mentioned that you still have the status ping stuff to do right? Could we maybe PR it without status ping, and then make a separate PR for status ping? Or is there some other stuff that needs to be done too?

**Comment by DSep** [comment]
No worries, yeah I imagined there was something else needing this. That plan sounds good. In terms of radio_controller input refactoring, status ping is all that remains. I estimate I'll have time to do it by Thurs. I'll open a draft PR but it depends on what timeline you need it for whether I get the status ping into it before merge. Let's discuss this online too ideally.

**Comment by SilentSys** [comment]
> No worries, yeah I imagined there was something else needing this. That plan sounds good. In terms of radio_controller input refactoring, status ping is all that remains. I estimate I'll have time to do it by Thurs. I'll open a draft PR but it depends on what timeline you need it for whether I get the status ping into it before merge. Let's discuss this online too ideally.

@DSep Thursday sounds great. We can hold off until then. If something happens and we cant get status ping by Thursday, I think its perfectly okay to PR them separately and just get what you have so far in on Thursday.

**Comment by SilentSys** [comment]
[Setup radio config packet, spec and parsing](https://trello.com/c/BojfddN7/231-setup-radio-config-packet-spec-and-parsing)

**Comment by SilentSys** [comment]
Branch has changed scope.

**Pull request closed without merging**
